using Microsoft.EntityFrameworkCore;

namespace ControleGastos.Api.Data;

/// <summary>
/// Ponte para bancos que já existem.
/// <para>
/// O projeto ainda não usa migrations: o schema nasce do <c>EnsureCreated</c>, que
/// só age em banco vazio. Quando o modelo ganha uma tabela nova, quem já tinha
/// dados ficaria sem ela — e a aplicação quebraria na primeira consulta.
/// </para>
/// <para>
/// Cada bloco aqui é <b>idempotente</b> (<c>IF NOT EXISTS</c>): em banco novo o
/// EnsureCreated já criou tudo e isto vira no-op; em banco antigo, completa o que
/// falta sem tocar nos dados existentes. Ao gerar a primeira migration do EF Core,
/// esta classe pode ser apagada e a chamada removida do <c>Program.cs</c>.
/// </para>
/// </summary>
public static class SchemaUpdates
{
    private static readonly string[] Statements =
    [
        // v2 — metas e aportes mensais
        """
        CREATE TABLE IF NOT EXISTS goals (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "Name" character varying(80) NOT NULL,
            "TargetAmount" numeric(18,2) NOT NULL,
            "TargetYear" integer NOT NULL,
            "TargetMonth" integer NOT NULL,
            "CategoryId" integer NOT NULL,
            "IsActive" boolean NOT NULL DEFAULT TRUE,
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
            CONSTRAINT "PK_goals" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_goals_categories_CategoryId"
                FOREIGN KEY ("CategoryId") REFERENCES categories ("Id") ON DELETE RESTRICT
        );
        """,
        """
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_goals_Name" ON goals ("Name");
        """,
        """
        CREATE TABLE IF NOT EXISTS goal_contributions (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "MonthlyPlanId" integer NOT NULL,
            "GoalId" integer NOT NULL,
            "Amount" numeric(18,2) NOT NULL,
            CONSTRAINT "PK_goal_contributions" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_goal_contributions_monthly_plans_MonthlyPlanId"
                FOREIGN KEY ("MonthlyPlanId") REFERENCES monthly_plans ("Id") ON DELETE CASCADE,
            CONSTRAINT "FK_goal_contributions_goals_GoalId"
                FOREIGN KEY ("GoalId") REFERENCES goals ("Id") ON DELETE RESTRICT
        );
        """,
        """
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_goal_contributions_MonthlyPlanId_GoalId"
            ON goal_contributions ("MonthlyPlanId", "GoalId");
        """
    ];

    public static async Task ApplyAsync(AppDbContext db, CancellationToken ct = default)
    {
        foreach (var statement in Statements)
            await db.Database.ExecuteSqlRawAsync(statement, ct);
    }
}
